Compiling ... : /home/lildurden/Documents/essais/sfml/game/asm/intersect.s
Compiling ... : /home/lildurden/Documents/essais/sfml/game/obj/map.o
Compiling ... : /home/lildurden/Documents/essais/sfml/game/obj/Circle.o
Compiling ... : /home/lildurden/Documents/essais/sfml/game/obj/controle.o
Compiling ... : /home/lildurden/Documents/essais/sfml/game/obj/files.o
Compiling ... : /home/lildurden/Documents/essais/sfml/game/obj/Rectangle.o
Compiling ... : /home/lildurden/Documents/essais/sfml/game/obj/still2d.o
Compiling ... : /home/lildurden/Documents/essais/sfml/game/obj/prologparse.o
Compiling ... : /home/lildurden/Documents/essais/sfml/game/obj/mobile2d.o
Compiling ... : /home/lildurden/Documents/essais/sfml/game/obj/mgame.o
